# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fbf5b6c95d776687234a55359d2dbbe948359bebed9914f2b002e90fe917de2ffbd0c9a79b4d7aed527ee28305630c27a2f666d6a467ea7d6f2aaf6c356e050

test:
  secret_key_base: 61b4ae7be39d56d797a3cca0cb187ec485abc28f778582620c9e988efdd4b72cd13e12df1f936fc7ebfea1ae33ebe121dc435d4d600281ac19b1d900da5b0fcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
